### ISSUE TITLE
The 'authorize_handler' does not handle HEAD requests

### ISSUE THREAD

**Issue by aegarbutt** [lepture/flask-oauthlib#172]
Flask implicitly routes HEAD requests to functions that accept a GET. However, it doesn't provide false witness what the request type actually is. In the 'authorize_handler' decorator, you have an explicit check "if request.method == 'GET'".

This means that HEAD requests are not processed as GET requests (as they should be).

**Comment by aegarbutt** [comment]
Sorry, I hit enter too early. This means that scopes and credentials aren't being parsed out of HEAD requests. This is causing errors for our decorated method.

In flask-oauthlib v.0.5.0, there was an explicit check for 'GET' and a separate explicit check for 'POST'. This resulted in returning a 500 because no response was generated.

**Comment by tranminhh** [comment]
It's worth noting that if you upgrade to v0.8.0, it no longer 500s due to `ValueError: View function did not return a response`. However, because the `if request.method == 'GET'` check is still there, in the HEAD code path, the request parameters are not validated and passed on the same way as it is for GET

My pull request should address this. Thanks!
