### ISSUE TITLE
require_login decorator not in sample code

### ISSUE THREAD

**Issue by kphretiq** [lepture/flask-oauthlib#303]
I may be misunderstanding the documentation, but I see no ```@require_login``` decorator in the sample code. Am I missing something?

**Comment by mihow** [comment]
Looking for this too. It would be great to have some usable examples in the docs.

**Comment by lepture** [comment]
@kphretiq the `@require_login` is not a part of this lib. It is a hint that you should decorate this handler with `@require_login`.

**Comment by ibrewster** [comment]
From the documentation:

> **There is a @require_login decorator in the sample code**, you should implement it yourself. [emphasis mine]

So either the documentation is wrong and needs to be fixed, or the decorator should be added to the sample code.

Personally, I'm struggling with how to implement this. I have a decorator, and it displays a login page on GET, but I haven't figured out what to do on post, since the decorator (as I have it written) looses all the oAuth stuff. Having a basic working example of this sort of a decorator would be extremely useful.

**Comment by dwatrous** [comment]
I think that comment means the sample that appears directly above that line, not elsewhere in another file. Here's an example of a decorator that ensures someone is logged in. Since flask-oauthlib doesn't provide a function to ensure a valid login has occurred, you'll have to do something else, like validate the token...

**Comment by dwatrous** [comment]
Here's an example that helped me get this to work:
http://flask.pocoo.org/docs/0.12/patterns/viewdecorators/#login-required-decorator

**Comment by lepture** [comment]
@dwatrous thanks. I've added the link into documentation.
