### ISSUE TITLE
Changing username to email for authentication

### ISSUE THREAD

**Issue by Gh9994** [lepture/flask-oauthlib#312]
I want to change the parameter `username` to `email` when authenticating with my OAuth2 provider for ease of understanding of my API. I looked through the code for OAuthlib and was able to change it server side in `/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py` however this would be a bad idea since it would mean that my code will not be portable as I'd have to change the file every time.

While I know that this problem involves mostly OAuthlib, I would not be sure how to implement it using Flask-OAuthlib. Would there be a potential solution my issue?

**Comment by ffleandro** [comment]
I don't know if it will work, but maybe you create a decorator that decorates `oauth.token_handler`.
In this decorator you can get the `email` parameter from the request and set `request.username = email` so that everything works fine from that point on.
Could this work? It's simple and doesn't imply any changes in the frameworks involved.

**Comment by ffleandro** [comment]
If you're still needing this feature, I can create a sample code to explain better, but I think it's possible with very little code and no alterations to any of the frameworks.
